CREATE TABLE IF NOT EXISTS category 
(
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name TEXT NOT NULL,
	discount NUMERIC(8,5) NOT NULL,
	money_required NUMERIC(15,2) NOT NULL,
	CONSTRAINT valid_discount CHECK (discount >= 0 AND discount <= 100),
	CONSTRAINT valid_money_reuqired CHECK (money_required >= 0.0)
);

CREATE TABLE IF NOT EXISTS client
(
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name TEXT NOT NULL,
	surname TEXT NOT NULL,
	email TEXT NOT NULL,
	category_id INT REFERENCES category (id) ON DELETE CASCADE,
	sex CHAR NOT NULL,
	CONSTRAINT valid_sex CHECK (sex = 'm' OR sex = 'f')
);

CREATE TABLE IF NOT EXISTS orders
(
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	client_id INT REFERENCES client (id)  ON DELETE CASCADE,
	session_start TIMESTAMP WITH TIME ZONE NOT NULL,
	session_end TIMESTAMP WITH TIME ZONE NOT NULL,
	computer INT NOT NULL,
	price NUMERIC(15,2),
	CONSTRAINT valid_session_time CHECK (session_end > session_start AND (session_end - session_start) < '1 day'::interval)
);

CREATE TABLE IF NOT EXISTS snack
(
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name TEXT NOT NULL,
	calories INT NOT NULL,
	price NUMERIC(15,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS snack_orders
(
	order_id INT REFERENCES orders (id) ON DELETE CASCADE,
	snack_id INT REFERENCES snack (id) ON DELETE CASCADE,
	amount INT,
	CONSTRAINT valid_amount CHECK (amount > 0)
);